// <auto-generated />
using ArticleApp.Repository.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArticleApp.Repository.Migrations
{
    [DbContext(typeof(ArticleAppDbContext))]
    [Migration("20220630173008_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ArticleApp.Core.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ArticleText")
                        .IsRequired()
                        .HasMaxLength(3500)
                        .HasColumnType("nvarchar(3500)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleText = "How much information is enough? How much is too much? And, most importantly, how much information is optimal?Information foraging gives us a way to formally model user trade-offs in deciding how much to read on your website. More precisely, diet selection is a modeling tool that tells us what food animals will eat and what articles users will read. In both scenarios, animals and people decide what to consume in a way that optimizes their benefits relative to the costs.For example, say a forest is inhabited by large and small rabbits. Which will the wolf eat? ",
                            AuthorId = 1,
                            CategoryId = 1,
                            Name = "Long vs. Short Articles as Content Strategy",
                            Summary = "Information foraging shows how to calculate your content strategy's costs and benefits. A mixed diet that combines brief overviews and comprehensive coverage is often best."
                        },
                        new
                        {
                            Id = 2,
                            ArticleText = "Luxury brands maintain their status by being exclusive. Any brand that becomes perceived as too common or available risks losing its “luxury” character. Price is a factor in restricting availability, but many luxury brands remain exclusive through other strategies as well. One strategy is increasing demand by limiting supply, as illustrated by the Hermès Birkin bag. Hermès intentionally manufactures a tiny number of these bags each year, despite extremely high demand. By refusing to meet demand, Hermès maintains the bag’s identity as a status symbol.In addition, Hermès uses another strategy to maintain the Birkin bag’s status — the company intentionally makes it difficult to find and buy this line of bags. They are not sold online or displayed in stores. Hermès used to offer a years-long waiting list, but even that is no longer available. Besides paying tens or hundreds of thousands of US dollars to buy a resold bag from a third party, the only way to obtain a Birkin is to be deemed worthy by Hermès — only their top customers receive invitations to buy.",
                            AuthorId = 2,
                            CategoryId = 2,
                            Name = "Applying Luxury Principles to Ecommerce Design",
                            Summary = "Luxury brands should use their digital channels to support and enhance their high-quality customer experiences. This requires providing product details that spark interest, balancing visual design with other priorities, and avoiding interruptions that risk cheapening the brand"
                        },
                        new
                        {
                            Id = 3,
                            ArticleText = "Most journey maps follow a similar format: at the top, a specific user, a specific scenario, and corresponding expectations or goals in the middle, high-level phases that are comprised of user actions, thoughts, and emotions;  at the bottom, the takeaways: opportunities, insights, and internal ownership.The terms ‘user journey map’ and ‘customer journey map’ can be used interchangeably. Both reference a visualization of a person using your product or service. While the argument can be made that the term ‘customer’ does a disservice to the method (because, especially for certain business-to-business products, not all of end users are technically customers, i.e., product buyers), alignment on what you call the map is far less important than alignment on the content within the map",
                            AuthorId = 3,
                            CategoryId = 3,
                            Name = "Journey Mapping 101",
                            Summary = "A journey map is a visualization of the process that a person goes through in order to accomplish a goal."
                        },
                        new
                        {
                            Id = 4,
                            ArticleText = "Good UX documentation ensures that everyone stays informed and helps Agile projects run smoothly. When the right information is captured at the right level of detail and in the right places, it’s not wasteful. Good documentation leads to better and faster decision making, aids in presenting and justifying design decisions, and reduces the cognitive load for the team by acting as a form of external memory. Keeping thought processes organized also builds trust and credibility for UX with stakeholders. In large organizations, good UX documentation that’s properly shared also helps with crossfunctional coordination.",
                            AuthorId = 3,
                            CategoryId = 4,
                            Name = "UX Documentation in Agile",
                            Summary = "Documenting UX processes and design decisions are organizational memory, so even Agile projects that emphasize minimal documentation benefit from two cases of lightweight UX documentation."
                        });
                });

            modelBuilder.Entity("ArticleApp.Core.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jakobnielsen@article.com",
                            Name = "Jakob Nielsen"
                        },
                        new
                        {
                            Id = 2,
                            Email = "katemoran@article.com",
                            Name = "Kate Moran"
                        },
                        new
                        {
                            Id = 3,
                            Email = "sarahgibbons@article.com",
                            Name = "Sarah Gibbons"
                        });
                });

            modelBuilder.Entity("ArticleApp.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A content strategy is an all-encompassing approach for creating content that drives key business objectives",
                            Name = "Content Strategy"
                        },
                        new
                        {
                            Id = 2,
                            Description = "E-commerce (electronic commerce) is the buying and selling of goods and services, or the transmitting of funds or data, over an electronic network, primarily the internet.",
                            Name = "Ecommerce"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The Design Process is an approach for breaking down a large project into manageable chunks. Architects, engineers, scientists, and other thinkers use the design process to solve a variety of problems.",
                            Name = "Design Process"
                        },
                        new
                        {
                            Id = 4,
                            Description = "agile is a group of methodologies that demonstrate a commitment to tight feedback cycles and continuous improvement.",
                            Name = "Agile"
                        });
                });

            modelBuilder.Entity("ArticleApp.Core.Models.Article", b =>
                {
                    b.HasOne("ArticleApp.Core.Models.Author", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArticleApp.Core.Models.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ArticleApp.Core.Models.Author", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("ArticleApp.Core.Models.Category", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
